test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    args.superuser = "package_checker"

    test_upgrade_from.1c884196.name = "3.2.0~ynh2"
    test_upgrade_from.cfc42dd5.name = "Last manifestv1 package"
